#!/bin/sh
# Combines the desktop and mobile crew widgets into one paste-ready responsive snippet.
# Switches on the width of the block it's placed in (not the screen), breakpoint 768px.
# The map image is inlined as a data URI so the snippet has no external files.
# Re-run after editing either source file.
set -e
cd "$(dirname "$0")"
out=crew-widget-responsive.html
map="data:image/jpeg;base64,$(base64 -i assets/routes-map.jpg | tr -d '\n')"
{
  cat <<'EOF'
<!-- Perennial — Animated Crew Scheduling Widget (responsive). GENERATED by build.sh; edit crew-widget.html / crew-widget-mobile.html instead. -->
<style>
  .pcw-responsive { container-type: inline-size; }
  .pcw-responsive > .pcwm { display: none; }
  @container (max-width: 767px) {
    .pcw-responsive > .pcw { display: none; }
    .pcw-responsive > .pcwm { display: block; }
  }
</style>
<div class="pcw-responsive">
EOF
  sed "s#assets/routes-map.jpg#${map}#" crew-widget.html
  sed '/<link /d' crew-widget-mobile.html
  echo '</div>'
} > "$out"
echo "Wrote $out ($(wc -c < "$out" | tr -d ' ') bytes)"
