#!/bin/sh
# Rebuilds every widget's responsive snippet, the all-widgets demo page, and the
# installable WordPress plugin zip.
set -e
cd "$(dirname "$0")"

for w in scheduling-widget crew-widget equipment-widget business-widget; do
  "./$w/build.sh"
done

# ---- demo.html: all four widgets on one self-contained page (works over file:// too) ----
{
  cat <<'HTML'
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Perennial Animated Widgets — Demo</title>
  <!-- GENERATED by build-all.sh. Scroll to play each widget; narrow the window under 768px for mobile. -->
  <style>
    body { margin: 0; background: #EEF1EF; font-family: system-ui, sans-serif; color: #24332B; }
    .demo-intro { max-width: 1200px; margin: 0 auto; padding: 48px 16px 8px; }
    .demo-intro h1 { margin: 0 0 8px; font-size: 24px; }
    .demo-intro p { margin: 0; font-size: 14px; color: #4A5A51; }
    .demo-item { max-width: 1200px; margin: 0 auto; padding: 40px 16px 80px; }
    .demo-item h2 { margin: 0 0 12px; font-size: 15px; font-weight: 600; color: #4A5A51; }
  </style>
</head>
<body>
  <div class="demo-intro">
    <h1>Perennial animated widgets</h1>
    <p>Each widget plays once when it scrolls into view. Narrow the window below 768px to see the mobile version.</p>
  </div>
HTML
  for w in scheduling-widget crew-widget equipment-widget business-widget; do
    title=$(echo "$w" | sed 's/-widget//; s/^./\U&/')
    printf '  <section class="demo-item">\n    <h2>%s</h2>\n' "$title"
    cat "$w/$w-responsive.html"
    printf '  </section>\n'
  done
  printf '</body>\n</html>\n'
} > demo.html
echo "Wrote demo.html ($(wc -c < demo.html | tr -d ' ') bytes)"

# ---- WordPress plugin ----
rm -rf dist/perennial-widgets
mkdir -p dist/perennial-widgets/widgets
cp plugin/perennial-widgets.php dist/perennial-widgets/
for w in scheduling-widget crew-widget equipment-widget business-widget; do
  cp "$w/$w-responsive.html" dist/perennial-widgets/widgets/
done
( cd dist && rm -f perennial-widgets.zip && zip -qr perennial-widgets.zip perennial-widgets )
echo "Wrote dist/perennial-widgets.zip ($(wc -c < dist/perennial-widgets.zip | tr -d ' ') bytes)"
