#!/bin/sh
# Combines the desktop and mobile equipment widgets into one paste-ready responsive snippet.
# Switches on the width of the block it's placed in (not the screen), breakpoint 768px.
# Re-run after editing either source file.
set -e
cd "$(dirname "$0")"
out=equipment-widget-responsive.html
{
  cat <<'HTML'
<!-- Perennial — Animated Equipment Insights Widget (responsive). GENERATED by build.sh; edit equipment-widget.html / equipment-widget-mobile.html instead. -->
<style>
  .pew-responsive { container-type: inline-size; }
  .pew-responsive > .pewm { display: none; }
  @container (max-width: 767px) {
    .pew-responsive > .pew { display: none; }
    .pew-responsive > .pewm { display: block; }
  }
</style>
<div class="pew-responsive">
HTML
  cat equipment-widget.html
  sed '/<link /d' equipment-widget-mobile.html
  echo '</div>'
} > "$out"
echo "Wrote $out ($(wc -c < "$out" | tr -d ' ') bytes)"
