#!/bin/sh
# Combines the desktop and mobile widgets into one paste-ready responsive snippet.
# Switches on the width of the block it's placed in (not the screen), breakpoint 768px.
# Re-run after editing either source file.
set -e
cd "$(dirname "$0")"
out=scheduling-widget-responsive.html
{
  cat <<'EOF'
<!-- Perennial — Animated Scheduling Widget (responsive). GENERATED by build.sh; edit the desktop/mobile files instead. -->
<style>
  .psw-responsive { container-type: inline-size; }
  .psw-responsive > .pswm { display: none; }
  @container (max-width: 767px) {
    .psw-responsive > .psw { display: none; }
    .psw-responsive > .pswm { display: block; }
  }
</style>
<div class="psw-responsive">
EOF
  cat scheduling-widget.html
  sed '/<link /d' scheduling-widget-mobile.html
  echo '</div>'
} > "$out"
echo "Wrote $out"
