#!/bin/sh
# Combines the desktop and mobile business overview widgets into one paste-ready responsive snippet.
# Switches on the width of the block it's placed in (not the screen), breakpoint 768px.
# Re-run after editing either source file.
set -e
cd "$(dirname "$0")"
out=business-widget-responsive.html
{
  cat <<'HTML'
<!-- Perennial — Animated Business Overview Widget (responsive). GENERATED by build.sh; edit business-widget.html / business-widget-mobile.html instead. -->
<style>
  .pbo-responsive { container-type: inline-size; }
  .pbo-responsive > .pbom { display: none; }
  @container (max-width: 767px) {
    .pbo-responsive > .pbo { display: none; }
    .pbo-responsive > .pbom { display: block; }
  }
</style>
<div class="pbo-responsive">
HTML
  cat business-widget.html
  sed '/<link /d' business-widget-mobile.html
  echo '</div>'
} > "$out"
echo "Wrote $out ($(wc -c < "$out" | tr -d ' ') bytes)"
